describe('Automation Test Suite - Fixtures', function () {
  let lat1 = -75.254647687689987;
  const newLat = Math.floor(Math.random() * -13) + lat1
  context('post /CreateContract', () => {
    this.beforeEach(function () {
      cy.fixture('object_Data').then(function (testdata) {
        this.testdata = testdata;
      })
    })
    it('should create a new contract', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetName: "AutoGenerated-Land",
          assetType: "land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: newLat,
          lon: 86.73623532,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.body.data).to.contain.keys(this.testdata.createAssests)
          expect(response.status).eq(this.testdata.okStatus)
          // expect(response.status).to.eq(422) 
        })
    })
  })
  {
    it('should not create asset if lat is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetName: "AutoGenerated-Land",
          assetType: "land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: -75.22145087,
          lon: 86.73623532,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(400)
        })
    })
  }
  {
    it('should not create asset if assetName is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetType: "land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: newLat,
          lon: 86.73623532,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(422)
        })
    })
  }
  {
    it('should not create asset if assetType is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetName: "AutoGenerated-Land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: newLat,
          lon: 86.73623532,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(422)
        })
    })
  }
  {
    it('should not create asset if seasonName is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetType: "land",
          assetStatus: "available",
          lat: newLat,
          lon: 86.73623532,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(422)
        })
    })
  }
  {
    it('should not create asset if assetStatus is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetType: "land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: newLat,
          lon: "86.73623532",
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(422)
        })
    })
  }
  {
    it('should not create asset if lon is missing ', function () {
      cy.request({
        method: this.testdata.post,
        url: this.testdata.CreateAssetsURL,
        body:
        {
          contractId: 1,
          ownerId: null,
          imageName: "https://staging-assets.wrld.xyz/staging/WLM3mCfReZUXlJ7DN4e5.png",
          animationName: "https://staging-assets.wrld.xyz/staging/KfQJmOvDEbFZQOpFB6j4.glb",
          assetLocation: "[[[0.009605007370914,-0.019960192287258],[0.010503322566252,-0.019960591652487],[0.010502923201023,-0.020858906790981],[0.009604608005686,-0.020858507425739],[0.009605007370914,-0.019960192287258]]]",
          price: 2.0,
          assetType: "land",
          seasonName: "season-1",
          assetStatus: "available",
          lat: newLat,
          isActive: true
        },
        headers: { "Cookie": this.testdata.btoken }, failOnStatusCode: false
      }).then(
        (response) => {
          expect(response.status).eq(422)
        })
    })
  }
})
